version: "3"
services:
  nginx:
    container_name: lnmp-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html/:rw
      - ./etc/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx:/var/log/nginx:rw
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      - networking
  php:
    container_name: lnmp-php
    build:
      context: ./etc/
      dockerfile: dockerfile-php
      args:
        buildno: 1
        TZ: Asia/Shanghai
    volumes:
      - ./html:/var/www/html/:rw
      - ./etc/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log/php
    restart: always
    networks:
      - networking
  mysql:
    container_name: lnmp-mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
    networks:
      - networking
  redis:
    container_name: lnmp-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis.conf:/etc/redis.conf:ro
      - ./redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: Asia/Shanghai
    networks:
      - networking
networks:
  networking: