FROM php:7.4.3-fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && sh -c '/bin/echo -e "\n\n\n" | pecl install -f redis' && docker-php-ext-enable redis \
    && sh -c '/bin/echo -e "\n\n\n" | pecl install -f mcrypt'&& docker-php-ext-enable mcrypt \
    && php -m